### ISSUE TITLE
fails to start since latest update

### ISSUE THREAD

**Issue by zocker-160** [flathub/net.davidotek.pupgui2#3]
```
$ flatpak run net.davidotek.pupgui2 
Traceback (most recent call last):
  File "/app/src/pupgui2/pupgui2.py", line 12, in <module>
    from steamutil import get_steam_game_list
  File "/app/src/pupgui2/steamutil.py", line 3, in <module>
    from steam.utils.appcache import parse_appinfo
ModuleNotFoundError: No module named 'steam'
```

**Comment by DavidoTek** [comment]
See https://github.com/DavidoTek/ProtonUp-Qt/issues/58
